package com.example.service.impl;

import com.example.pdf.MyHtmlConverter;
import com.example.service.PdfGenerator;
import com.itextpdf.html2pdf.ConverterProperties;
import com.itextpdf.html2pdf.attach.impl.OutlineHandler;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.WriterProperties;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.font.FontProvider;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Service;

import javax.servlet.http.HttpServletResponse;
import java.io.*;
import java.net.URLDecoder;
import java.util.Calendar;
import java.util.UUID;

@Service
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class PdfGeneratorServicelmpl implements PdfGenerator {
    private FontProvider fontProvider;

    @Override
    public void generatePdf(HttpServletResponse response) throws Exception {
//        //获取css内容
//        String css = params.getString("css");
//        //获取html内容
//        String html = params.getString("html");
//        //拼接
//        String cont = "<html><head><style>"+ css +"</style></head><body>"+ html +"</body></html>";



        //调用方法生成pdf返回
        getGen(content,response);
    }

    public void getGen(String cont,HttpServletResponse response) throws IOException {
        //获取字体文件
//        initFont();
        //先给个固定目录要确保你E盘下有pdf文件如果没有自己手动创建
        String outputFile="E:/liuce";
        //按当前日期生成目录--样式--/年/月/日
        //String generateSavePath = generateSavePath();
        //拼接目录--E:/pdf/年/月/日
        String serverFilePath = outputFile;
        File flvDir = new File(serverFilePath);
        //判断当前目录有文件没
        if (!flvDir.exists()) {
            //没有生成
            flvDir.mkdirs();
        }
        //创建个pdf名
        UUID uuid = UUID.randomUUID();
        //当前目录加pdf名
        String filePath = serverFilePath  + uuid + ".pdf";

        //outputFile也可以是输出流
        PdfWriter writer = new PdfWriter(filePath, new WriterProperties().setFullCompressionMode(Boolean.TRUE));
        PdfDocument doc    = new PdfDocument(writer);
        doc.setDefaultPageSize(PageSize.A4);
        doc.getDefaultPageSize().applyMargins(20, 20, 20, 20, true);


        ConverterProperties properties = new ConverterProperties();
        properties.setFontProvider(fontProvider);
        //PDF目录
        properties.setOutlineHandler(OutlineHandler.createStandardHandler());
        Document document = MyHtmlConverter.convertToPdf(cont, doc, properties);

        document.close();
        //写入响应
        extracted(filePath,response);
    }

    /**
     *  响应
     * @param outputFile
     * @param response
     * @throws UnsupportedEncodingException
     */
    private void extracted(String outputFile,HttpServletResponse response) throws UnsupportedEncodingException {
        FileInputStream in;
        OutputStream out;
        response.setContentType("'application/pdf");
        String decode = URLDecoder.decode(outputFile, "UTF-8");
        try {
            in = new FileInputStream(new File(decode));
            out = response.getOutputStream();
            byte[] b = new byte[512];
            while ((in.read(b)) != -1) {
                out.write(b);
            }
            out.flush();
            in.close();
            out.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * 获取字体文件
     */
    private void initFont() {
//        fontProvider = new FontProvider();
        //设置中文字体文件的路径
//        fontProvider.addFont(fontpath());
    }

    /**
     * 根据当前日期生成文件层级存放pdf
     * @return
     */
    private String generateSavePath() {
        Calendar calendar = Calendar.getInstance();
        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH) + 1;
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        return "/" + year + "/" + month + "/" + day + "/";
    }

    String content = "        String cont = \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 4.01 Transitional//EN\\\" \\\"http://www.w3.org/TR/html4/loose.dtd\\\">\\n\" +\n" +
            "                \"<!-- NewPage -->\\n\" +\n" +
            "                \"<html lang=\\\"en\\\">\\n\" +\n" +
            "                \"<head>\\n\" +\n" +
            "                \"<!-- Generated by javadoc (1.8.0_282) on Fri Feb 25 08:50:52 UTC 2022 -->\\n\" +\n" +
            "                \"<meta http-equiv=\\\"Content-Type\\\" content=\\\"text/html; charset=UTF-8\\\">\\n\" +\n" +
            "                \"<title>ZooKeeperSaslClient (Apache ZooKeeper - Server 3.8.0 API)</title>\\n\" +\n" +
            "                \"<meta name=\\\"date\\\" content=\\\"2022-02-25\\\">\\n\" +\n" +
            "                \"<link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"../../../../stylesheet.css\\\" title=\\\"Style\\\">\\n\" +\n" +
            "                \"<script type=\\\"text/javascript\\\" src=\\\"../../../../script.js\\\"></script>\\n\" +\n" +
            "                \"</head>\\n\" +\n" +
            "                \"<body>\\n\" +\n" +
            "                \"<script type=\\\"text/javascript\\\"><!--\\n\" +\n" +
            "                \"    try {\\n\" +\n" +
            "                \"        if (location.href.indexOf('is-external=true') == -1) {\\n\" +\n" +
            "                \"            parent.document.title=\\\"ZooKeeperSaslClient (Apache ZooKeeper - Server 3.8.0 API)\\\";\\n\" +\n" +
            "                \"        }\\n\" +\n" +
            "                \"    }\\n\" +\n" +
            "                \"    catch(err) {\\n\" +\n" +
            "                \"    }\\n\" +\n" +
            "                \"//-->\\n\" +\n" +
            "                \"var methods = {\\\"i0\\\":10,\\\"i1\\\":10,\\\"i2\\\":10,\\\"i3\\\":10,\\\"i4\\\":10,\\\"i5\\\":10,\\\"i6\\\":10,\\\"i7\\\":41,\\\"i8\\\":10,\\\"i9\\\":10,\\\"i10\\\":10};\\n\" +\n" +
            "                \"var tabs = {65535:[\\\"t0\\\",\\\"All Methods\\\"],1:[\\\"t1\\\",\\\"Static Methods\\\"],2:[\\\"t2\\\",\\\"Instance Methods\\\"],8:[\\\"t4\\\",\\\"Concrete Methods\\\"],32:[\\\"t6\\\",\\\"Deprecated Methods\\\"]};\\n\" +\n" +
            "                \"var altColor = \\\"altColor\\\";\\n\" +\n" +
            "                \"var rowColor = \\\"rowColor\\\";\\n\" +\n" +
            "                \"var tableTab = \\\"tableTab\\\";\\n\" +\n" +
            "                \"var activeTableTab = \\\"activeTableTab\\\";\\n\" +\n" +
            "                \"</script>\\n\" +\n" +
            "                \"<noscript>\\n\" +\n" +
            "                \"<div>JavaScript is disabled on your browser.</div>\\n\" +\n" +
            "                \"</noscript>\\n\" +\n" +
            "                \"<!-- ========= START OF TOP NAVBAR ======= -->\\n\" +\n" +
            "                \"<div class=\\\"topNav\\\"><a name=\\\"navbar.top\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<div class=\\\"skipNav\\\"><a href=\\\"#skip.navbar.top\\\" title=\\\"Skip navigation links\\\">Skip navigation links</a></div>\\n\" +\n" +
            "                \"<a name=\\\"navbar.top.firstrow\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\" title=\\\"Navigation\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../overview-summary.html\\\">Overview</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"package-summary.html\\\">Package</a></li>\\n\" +\n" +
            "                \"<li class=\\\"navBarCell1Rev\\\">Class</li>\\n\" +\n" +
            "                \"<li><a href=\\\"class-use/ZooKeeperSaslClient.html\\\">Use</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"package-tree.html\\\">Tree</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../deprecated-list.html\\\">Deprecated</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../index-all.html\\\">Index</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../help-doc.html\\\">Help</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div class=\\\"subNav\\\">\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html\\\" title=\\\"class in org.apache.zookeeper.client\\\"><span class=\\\"typeNameLink\\\">Prev&nbsp;Class</span></a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.SaslState.html\\\" title=\\\"enum in org.apache.zookeeper.client\\\"><span class=\\\"typeNameLink\\\">Next&nbsp;Class</span></a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../index.html?org/apache/zookeeper/client/ZooKeeperSaslClient.html\\\" target=\\\"_top\\\">Frames</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"ZooKeeperSaslClient.html\\\" target=\\\"_top\\\">No&nbsp;Frames</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\" id=\\\"allclasses_navbar_top\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../allclasses-noframe.html\\\">All&nbsp;Classes</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<div>\\n\" +\n" +
            "                \"<script type=\\\"text/javascript\\\"><!--\\n\" +\n" +
            "                \"  allClassesLink = document.getElementById(\\\"allclasses_navbar_top\\\");\\n\" +\n" +
            "                \"  if(window==top) {\\n\" +\n" +
            "                \"    allClassesLink.style.display = \\\"block\\\";\\n\" +\n" +
            "                \"  }\\n\" +\n" +
            "                \"  else {\\n\" +\n" +
            "                \"    allClassesLink.style.display = \\\"none\\\";\\n\" +\n" +
            "                \"  }\\n\" +\n" +
            "                \"  //-->\\n\" +\n" +
            "                \"</script>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div>\\n\" +\n" +
            "                \"<ul class=\\\"subNavList\\\">\\n\" +\n" +
            "                \"<li>Summary:&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#nested.class.summary\\\">Nested</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#field.summary\\\">Field</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#constructor.summary\\\">Constr</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#method.summary\\\">Method</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<ul class=\\\"subNavList\\\">\\n\" +\n" +
            "                \"<li>Detail:&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#field.detail\\\">Field</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#constructor.detail\\\">Constr</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#method.detail\\\">Method</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<a name=\\\"skip.navbar.top\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a></div>\\n\" +\n" +
            "                \"<!-- ========= END OF TOP NAVBAR ========= -->\\n\" +\n" +
            "                \"<!-- ======== START OF CLASS DATA ======== -->\\n\" +\n" +
            "                \"<div class=\\\"header\\\">\\n\" +\n" +
            "                \"<div class=\\\"subTitle\\\">org.apache.zookeeper.client</div>\\n\" +\n" +
            "                \"<h2 title=\\\"Class ZooKeeperSaslClient\\\" class=\\\"title\\\">Class ZooKeeperSaslClient</h2>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div class=\\\"contentContainer\\\">\\n\" +\n" +
            "                \"<ul class=\\\"inheritance\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">java.lang.Object</a></li>\\n\" +\n" +
            "                \"<li>\\n\" +\n" +
            "                \"<ul class=\\\"inheritance\\\">\\n\" +\n" +
            "                \"<li>org.apache.zookeeper.client.ZooKeeperSaslClient</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<div class=\\\"description\\\">\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<hr>\\n\" +\n" +
            "                \"<br>\\n\" +\n" +
            "                \"<pre>public class <span class=\\\"typeNameLabel\\\">ZooKeeperSaslClient</span>\\n\" +\n" +
            "                \"extends <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">Object</a></pre>\\n\" +\n" +
            "                \"<div class=\\\"block\\\">This class manages SASL authentication for the client. It\\n\" +\n" +
            "                \" allows ClientCnxn to authenticate using SASL with a ZooKeeper server.</div>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div class=\\\"summary\\\">\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<!-- ======== NESTED CLASS SUMMARY ======== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"nested.class.summary\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Nested Class Summary</h3>\\n\" +\n" +
            "                \"<table class=\\\"memberSummary\\\" border=\\\"0\\\" cellpadding=\\\"3\\\" cellspacing=\\\"0\\\" summary=\\\"Nested Class Summary table, listing nested classes, and an explanation\\\">\\n\" +\n" +
            "                \"<caption><span>Nested Classes</span><span class=\\\"tabEnd\\\">&nbsp;</span></caption>\\n\" +\n" +
            "                \"<tr>\\n\" +\n" +
            "                \"<th class=\\\"colFirst\\\" scope=\\\"col\\\">Modifier and Type</th>\\n\" +\n" +
            "                \"<th class=\\\"colLast\\\" scope=\\\"col\\\">Class and Description</th>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>static class&nbsp;</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.SaslState.html\\\" title=\\\"enum in org.apache.zookeeper.client\\\">ZooKeeperSaslClient.SaslState</a></span></code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>static class&nbsp;</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.ServerSaslResponseCallback.html\\\" title=\\\"class in org.apache.zookeeper.client\\\">ZooKeeperSaslClient.ServerSaslResponseCallback</a></span></code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"</table>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<!-- =========== FIELD SUMMARY =========== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"field.summary\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Field Summary</h3>\\n\" +\n" +
            "                \"<table class=\\\"memberSummary\\\" border=\\\"0\\\" cellpadding=\\\"3\\\" cellspacing=\\\"0\\\" summary=\\\"Field Summary table, listing fields, and an explanation\\\">\\n\" +\n" +
            "                \"<caption><span>Fields</span><span class=\\\"tabEnd\\\">&nbsp;</span></caption>\\n\" +\n" +
            "                \"<tr>\\n\" +\n" +
            "                \"<th class=\\\"colFirst\\\" scope=\\\"col\\\">Modifier and Type</th>\\n\" +\n" +
            "                \"<th class=\\\"colLast\\\" scope=\\\"col\\\">Field and Description</th>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>static <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#ENABLE_CLIENT_SASL_DEFAULT\\\">ENABLE_CLIENT_SASL_DEFAULT</a></span></code>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#ENABLE_CLIENT_SASL_DEFAULT\\\"><code>ZKClientConfig.ENABLE_CLIENT_SASL_DEFAULT</code></a>\\n\" +\n" +
            "                \"             instead.</span></div>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>static <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#ENABLE_CLIENT_SASL_KEY\\\">ENABLE_CLIENT_SASL_KEY</a></span></code>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#ENABLE_CLIENT_SASL_KEY\\\"><code>ZKClientConfig.ENABLE_CLIENT_SASL_KEY</code></a>\\n\" +\n" +
            "                \"             instead.</span></div>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>static <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#LOGIN_CONTEXT_NAME_KEY\\\">LOGIN_CONTEXT_NAME_KEY</a></span></code>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#LOGIN_CONTEXT_NAME_KEY\\\"><code>ZKClientConfig.LOGIN_CONTEXT_NAME_KEY</code></a>\\n\" +\n" +
            "                \"             instead.</span></div>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"</table>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<!-- ======== CONSTRUCTOR SUMMARY ======== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"constructor.summary\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Constructor Summary</h3>\\n\" +\n" +
            "                \"<table class=\\\"memberSummary\\\" border=\\\"0\\\" cellpadding=\\\"3\\\" cellspacing=\\\"0\\\" summary=\\\"Constructor Summary table, listing constructors, and an explanation\\\">\\n\" +\n" +
            "                \"<caption><span>Constructors</span><span class=\\\"tabEnd\\\">&nbsp;</span></caption>\\n\" +\n" +
            "                \"<tr>\\n\" +\n" +
            "                \"<th class=\\\"colOne\\\" scope=\\\"col\\\">Constructor and Description</th>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colOne\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#ZooKeeperSaslClient-java.lang.String-org.apache.zookeeper.client.ZKClientConfig-\\\">ZooKeeperSaslClient</a></span>(<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a>&nbsp;serverPrincipal,\\n\" +\n" +
            "                \"                   <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html\\\" title=\\\"class in org.apache.zookeeper.client\\\">ZKClientConfig</a>&nbsp;clientConfig)</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"</table>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<!-- ========== METHOD SUMMARY =========== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"method.summary\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Method Summary</h3>\\n\" +\n" +
            "                \"<table class=\\\"memberSummary\\\" border=\\\"0\\\" cellpadding=\\\"3\\\" cellspacing=\\\"0\\\" summary=\\\"Method Summary table, listing methods, and an explanation\\\">\\n\" +\n" +
            "                \"<caption><span id=\\\"t0\\\" class=\\\"activeTableTab\\\"><span>All Methods</span><span class=\\\"tabEnd\\\">&nbsp;</span></span><span id=\\\"t1\\\" class=\\\"tableTab\\\"><span><a href=\\\"javascript:show(1);\\\">Static Methods</a></span><span class=\\\"tabEnd\\\">&nbsp;</span></span><span id=\\\"t2\\\" class=\\\"tableTab\\\"><span><a href=\\\"javascript:show(2);\\\">Instance Methods</a></span><span class=\\\"tabEnd\\\">&nbsp;</span></span><span id=\\\"t4\\\" class=\\\"tableTab\\\"><span><a href=\\\"javascript:show(8);\\\">Concrete Methods</a></span><span class=\\\"tabEnd\\\">&nbsp;</span></span><span id=\\\"t6\\\" class=\\\"tableTab\\\"><span><a href=\\\"javascript:show(32);\\\">Deprecated Methods</a></span><span class=\\\"tabEnd\\\">&nbsp;</span></span></caption>\\n\" +\n" +
            "                \"<tr>\\n\" +\n" +
            "                \"<th class=\\\"colFirst\\\" scope=\\\"col\\\">Modifier and Type</th>\\n\" +\n" +
            "                \"<th class=\\\"colLast\\\" scope=\\\"col\\\">Method and Description</th>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i0\\\" class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>boolean</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#clientTunneledAuthenticationInProgress--\\\">clientTunneledAuthenticationInProgress</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i1\\\" class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#getConfigStatus--\\\">getConfigStatus</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i2\\\" class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code><a href=\\\"../../../../org/apache/zookeeper/Watcher.Event.KeeperState.html\\\" title=\\\"enum in org.apache.zookeeper\\\">Watcher.Event.KeeperState</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#getKeeperState--\\\">getKeeperState</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i3\\\" class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#getLoginContext--\\\">getLoginContext</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i4\\\" class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.SaslState.html\\\" title=\\\"enum in org.apache.zookeeper.client\\\">ZooKeeperSaslClient.SaslState</a></code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#getSaslState--\\\">getSaslState</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i5\\\" class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>void</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#initialize-org.apache.zookeeper.ClientCnxn-\\\">initialize</a></span>(<a href=\\\"../../../../org/apache/zookeeper/ClientCnxn.html\\\" title=\\\"class in org.apache.zookeeper\\\">ClientCnxn</a>&nbsp;cnxn)</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i6\\\" class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>boolean</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#isComplete--\\\">isComplete</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i7\\\" class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>static boolean</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#isEnabled--\\\">isEnabled</a></span>()</code>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#isSaslClientEnabled--\\\"><code>ZKClientConfig.isSaslClientEnabled()</code></a> instead</span></div>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i8\\\" class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>boolean</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#isFailed--\\\">isFailed</a></span>()</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i9\\\" class=\\\"rowColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>void</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#respondToServer-byte:A-org.apache.zookeeper.ClientCnxn-\\\">respondToServer</a></span>(byte[]&nbsp;serverToken,\\n\" +\n" +
            "                \"               <a href=\\\"../../../../org/apache/zookeeper/ClientCnxn.html\\\" title=\\\"class in org.apache.zookeeper\\\">ClientCnxn</a>&nbsp;cnxn)</code>&nbsp;</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"<tr id=\\\"i10\\\" class=\\\"altColor\\\">\\n\" +\n" +
            "                \"<td class=\\\"colFirst\\\"><code>void</code></td>\\n\" +\n" +
            "                \"<td class=\\\"colLast\\\"><code><span class=\\\"memberNameLink\\\"><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.html#shutdown--\\\">shutdown</a></span>()</code>\\n\" +\n" +
            "                \"<div class=\\\"block\\\">close login thread if running</div>\\n\" +\n" +
            "                \"</td>\\n\" +\n" +
            "                \"</tr>\\n\" +\n" +
            "                \"</table>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"methods.inherited.from.class.java.lang.Object\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Methods inherited from class&nbsp;java.lang.<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">Object</a></h3>\\n\" +\n" +
            "                \"<code><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#clone--\\\" title=\\\"class or interface in java.lang\\\">clone</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#equals-java.lang.Object-\\\" title=\\\"class or interface in java.lang\\\">equals</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#finalize--\\\" title=\\\"class or interface in java.lang\\\">finalize</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#getClass--\\\" title=\\\"class or interface in java.lang\\\">getClass</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#hashCode--\\\" title=\\\"class or interface in java.lang\\\">hashCode</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#notify--\\\" title=\\\"class or interface in java.lang\\\">notify</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#notifyAll--\\\" title=\\\"class or interface in java.lang\\\">notifyAll</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#toString--\\\" title=\\\"class or interface in java.lang\\\">toString</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait--\\\" title=\\\"class or interface in java.lang\\\">wait</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait-long-\\\" title=\\\"class or interface in java.lang\\\">wait</a>, <a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait-long-int-\\\" title=\\\"class or interface in java.lang\\\">wait</a></code></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div class=\\\"details\\\">\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<!-- ============ FIELD DETAIL =========== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"field.detail\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Field Detail</h3>\\n\" +\n" +
            "                \"<a name=\\\"LOGIN_CONTEXT_NAME_KEY\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>LOGIN_CONTEXT_NAME_KEY</h4>\\n\" +\n" +
            "                \"<pre><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Deprecated.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">@Deprecated</a>\\n\" +\n" +
            "                \"public static final&nbsp;<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a> LOGIN_CONTEXT_NAME_KEY</pre>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;<span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#LOGIN_CONTEXT_NAME_KEY\\\"><code>ZKClientConfig.LOGIN_CONTEXT_NAME_KEY</code></a>\\n\" +\n" +
            "                \"             instead.</span></div>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"seeLabel\\\">See Also:</span></dt>\\n\" +\n" +
            "                \"<dd><a href=\\\"../../../../constant-values.html#org.apache.zookeeper.client.ZooKeeperSaslClient.LOGIN_CONTEXT_NAME_KEY\\\">Constant Field Values</a></dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"ENABLE_CLIENT_SASL_KEY\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>ENABLE_CLIENT_SASL_KEY</h4>\\n\" +\n" +
            "                \"<pre><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Deprecated.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">@Deprecated</a>\\n\" +\n" +
            "                \"public static final&nbsp;<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a> ENABLE_CLIENT_SASL_KEY</pre>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;<span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#ENABLE_CLIENT_SASL_KEY\\\"><code>ZKClientConfig.ENABLE_CLIENT_SASL_KEY</code></a>\\n\" +\n" +
            "                \"             instead.</span></div>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"seeLabel\\\">See Also:</span></dt>\\n\" +\n" +
            "                \"<dd><a href=\\\"../../../../constant-values.html#org.apache.zookeeper.client.ZooKeeperSaslClient.ENABLE_CLIENT_SASL_KEY\\\">Constant Field Values</a></dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"ENABLE_CLIENT_SASL_DEFAULT\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockListLast\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>ENABLE_CLIENT_SASL_DEFAULT</h4>\\n\" +\n" +
            "                \"<pre><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Deprecated.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">@Deprecated</a>\\n\" +\n" +
            "                \"public static final&nbsp;<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a> ENABLE_CLIENT_SASL_DEFAULT</pre>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;<span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#ENABLE_CLIENT_SASL_DEFAULT\\\"><code>ZKClientConfig.ENABLE_CLIENT_SASL_DEFAULT</code></a>\\n\" +\n" +
            "                \"             instead.</span></div>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"seeLabel\\\">See Also:</span></dt>\\n\" +\n" +
            "                \"<dd><a href=\\\"../../../../constant-values.html#org.apache.zookeeper.client.ZooKeeperSaslClient.ENABLE_CLIENT_SASL_DEFAULT\\\">Constant Field Values</a></dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<!-- ========= CONSTRUCTOR DETAIL ======== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"constructor.detail\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Constructor Detail</h3>\\n\" +\n" +
            "                \"<a name=\\\"ZooKeeperSaslClient-java.lang.String-org.apache.zookeeper.client.ZKClientConfig-\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockListLast\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>ZooKeeperSaslClient</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;ZooKeeperSaslClient(<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a>&nbsp;serverPrincipal,\\n\" +\n" +
            "                \"                           <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html\\\" title=\\\"class in org.apache.zookeeper.client\\\">ZKClientConfig</a>&nbsp;clientConfig)\\n\" +\n" +
            "                \"                    throws <a href=\\\"https://docs.oracle.com/javase/8/docs/api/javax/security/auth/login/LoginException.html?is-external=true\\\" title=\\\"class or interface in javax.security.auth.login\\\">LoginException</a></pre>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"throwsLabel\\\">Throws:</span></dt>\\n\" +\n" +
            "                \"<dd><code><a href=\\\"https://docs.oracle.com/javase/8/docs/api/javax/security/auth/login/LoginException.html?is-external=true\\\" title=\\\"class or interface in javax.security.auth.login\\\">LoginException</a></code></dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<!-- ============ METHOD DETAIL ========== -->\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\"><a name=\\\"method.detail\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<h3>Method Detail</h3>\\n\" +\n" +
            "                \"<a name=\\\"isEnabled--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>isEnabled</h4>\\n\" +\n" +
            "                \"<pre><a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/Deprecated.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">@Deprecated</a>\\n\" +\n" +
            "                \"public static&nbsp;boolean&nbsp;isEnabled()</pre>\\n\" +\n" +
            "                \"<div class=\\\"block\\\"><span class=\\\"deprecatedLabel\\\">Deprecated.</span>&nbsp;<span class=\\\"deprecationComment\\\">Use <a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html#isSaslClientEnabled--\\\"><code>ZKClientConfig.isSaslClientEnabled()</code></a> instead</span></div>\\n\" +\n" +
            "                \"<div class=\\\"block\\\">Returns true if the SASL client is enabled. By default, the client\\n\" +\n" +
            "                \" is enabled but can be disabled by setting the system property\\n\" +\n" +
            "                \" <code>zookeeper.sasl.client</code> to <code>false</code>. See\\n\" +\n" +
            "                \" ZOOKEEPER-1657 for more information.</div>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"returnLabel\\\">Returns:</span></dt>\\n\" +\n" +
            "                \"<dd>true if the SASL client is enabled.</dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"getSaslState--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>getSaslState</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;<a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.SaslState.html\\\" title=\\\"enum in org.apache.zookeeper.client\\\">ZooKeeperSaslClient.SaslState</a>&nbsp;getSaslState()</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"getLoginContext--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>getLoginContext</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a>&nbsp;getLoginContext()</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"getConfigStatus--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>getConfigStatus</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;<a href=\\\"https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true\\\" title=\\\"class or interface in java.lang\\\">String</a>&nbsp;getConfigStatus()</pre>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"returnLabel\\\">Returns:</span></dt>\\n\" +\n" +
            "                \"<dd>informational message indicating the current configuration status.</dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"isComplete--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>isComplete</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;boolean&nbsp;isComplete()</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"isFailed--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>isFailed</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;boolean&nbsp;isFailed()</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"respondToServer-byte:A-org.apache.zookeeper.ClientCnxn-\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>respondToServer</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;void&nbsp;respondToServer(byte[]&nbsp;serverToken,\\n\" +\n" +
            "                \"                            <a href=\\\"../../../../org/apache/zookeeper/ClientCnxn.html\\\" title=\\\"class in org.apache.zookeeper\\\">ClientCnxn</a>&nbsp;cnxn)</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"getKeeperState--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>getKeeperState</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;<a href=\\\"../../../../org/apache/zookeeper/Watcher.Event.KeeperState.html\\\" title=\\\"enum in org.apache.zookeeper\\\">Watcher.Event.KeeperState</a>&nbsp;getKeeperState()</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"initialize-org.apache.zookeeper.ClientCnxn-\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>initialize</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;void&nbsp;initialize(<a href=\\\"../../../../org/apache/zookeeper/ClientCnxn.html\\\" title=\\\"class in org.apache.zookeeper\\\">ClientCnxn</a>&nbsp;cnxn)\\n\" +\n" +
            "                \"                throws <a href=\\\"https://docs.oracle.com/javase/8/docs/api/javax/security/sasl/SaslException.html?is-external=true\\\" title=\\\"class or interface in javax.security.sasl\\\">SaslException</a></pre>\\n\" +\n" +
            "                \"<dl>\\n\" +\n" +
            "                \"<dt><span class=\\\"throwsLabel\\\">Throws:</span></dt>\\n\" +\n" +
            "                \"<dd><code><a href=\\\"https://docs.oracle.com/javase/8/docs/api/javax/security/sasl/SaslException.html?is-external=true\\\" title=\\\"class or interface in javax.security.sasl\\\">SaslException</a></code></dd>\\n\" +\n" +
            "                \"</dl>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"clientTunneledAuthenticationInProgress--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>clientTunneledAuthenticationInProgress</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;boolean&nbsp;clientTunneledAuthenticationInProgress()</pre>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<a name=\\\"shutdown--\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"blockListLast\\\">\\n\" +\n" +
            "                \"<li class=\\\"blockList\\\">\\n\" +\n" +
            "                \"<h4>shutdown</h4>\\n\" +\n" +
            "                \"<pre>public&nbsp;void&nbsp;shutdown()</pre>\\n\" +\n" +
            "                \"<div class=\\\"block\\\">close login thread if running</div>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<!-- ========= END OF CLASS DATA ========= -->\\n\" +\n" +
            "                \"<!-- ======= START OF BOTTOM NAVBAR ====== -->\\n\" +\n" +
            "                \"<div class=\\\"bottomNav\\\"><a name=\\\"navbar.bottom\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<div class=\\\"skipNav\\\"><a href=\\\"#skip.navbar.bottom\\\" title=\\\"Skip navigation links\\\">Skip navigation links</a></div>\\n\" +\n" +
            "                \"<a name=\\\"navbar.bottom.firstrow\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a>\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\" title=\\\"Navigation\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../overview-summary.html\\\">Overview</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"package-summary.html\\\">Package</a></li>\\n\" +\n" +
            "                \"<li class=\\\"navBarCell1Rev\\\">Class</li>\\n\" +\n" +
            "                \"<li><a href=\\\"class-use/ZooKeeperSaslClient.html\\\">Use</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"package-tree.html\\\">Tree</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../deprecated-list.html\\\">Deprecated</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../index-all.html\\\">Index</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../help-doc.html\\\">Help</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div class=\\\"subNav\\\">\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../org/apache/zookeeper/client/ZKClientConfig.html\\\" title=\\\"class in org.apache.zookeeper.client\\\"><span class=\\\"typeNameLink\\\">Prev&nbsp;Class</span></a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../org/apache/zookeeper/client/ZooKeeperSaslClient.SaslState.html\\\" title=\\\"enum in org.apache.zookeeper.client\\\"><span class=\\\"typeNameLink\\\">Next&nbsp;Class</span></a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../index.html?org/apache/zookeeper/client/ZooKeeperSaslClient.html\\\" target=\\\"_top\\\">Frames</a></li>\\n\" +\n" +
            "                \"<li><a href=\\\"ZooKeeperSaslClient.html\\\" target=\\\"_top\\\">No&nbsp;Frames</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<ul class=\\\"navList\\\" id=\\\"allclasses_navbar_bottom\\\">\\n\" +\n" +
            "                \"<li><a href=\\\"../../../../allclasses-noframe.html\\\">All&nbsp;Classes</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<div>\\n\" +\n" +
            "                \"<script type=\\\"text/javascript\\\"><!--\\n\" +\n" +
            "                \"  allClassesLink = document.getElementById(\\\"allclasses_navbar_bottom\\\");\\n\" +\n" +
            "                \"  if(window==top) {\\n\" +\n" +
            "                \"    allClassesLink.style.display = \\\"block\\\";\\n\" +\n" +
            "                \"  }\\n\" +\n" +
            "                \"  else {\\n\" +\n" +
            "                \"    allClassesLink.style.display = \\\"none\\\";\\n\" +\n" +
            "                \"  }\\n\" +\n" +
            "                \"  //-->\\n\" +\n" +
            "                \"</script>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<div>\\n\" +\n" +
            "                \"<ul class=\\\"subNavList\\\">\\n\" +\n" +
            "                \"<li>Summary:&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#nested.class.summary\\\">Nested</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#field.summary\\\">Field</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#constructor.summary\\\">Constr</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#method.summary\\\">Method</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"<ul class=\\\"subNavList\\\">\\n\" +\n" +
            "                \"<li>Detail:&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#field.detail\\\">Field</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#constructor.detail\\\">Constr</a>&nbsp;|&nbsp;</li>\\n\" +\n" +
            "                \"<li><a href=\\\"#method.detail\\\">Method</a></li>\\n\" +\n" +
            "                \"</ul>\\n\" +\n" +
            "                \"</div>\\n\" +\n" +
            "                \"<a name=\\\"skip.navbar.bottom\\\">\\n\" +\n" +
            "                \"<!--   -->\\n\" +\n" +
            "                \"</a></div>\\n\" +\n" +
            "                \"<!-- ======== END OF BOTTOM NAVBAR ======= -->\\n\" +\n" +
            "                \"<p class=\\\"legalCopy\\\"><small>Copyright &#169; 2008&#x2013;2022 <a href=\\\"https://www.apache.org/\\\">The Apache Software Foundation</a>. All rights reserved.</small></p>\\n\" +\n" +
            "                \"</body>\\n\" +\n" +
            "                \"</html>\\n\"";
}
